export const contactList = [
  {
    id: 1,
    firstName: 'Denis',
    lastName: '',
    email: 'contact1@icloud.com',
    phoneNumber: '111',
    description: '',
    company: '',
    isBlocked: false,
  },
  {
    id: 2,
    firstName: 'Alex',
    lastName: '',
    email: 'contact2@icloud.com',
    phoneNumber: '222',
    description: '',
    company: '',
    isBlocked: false,
  },
  {
    id: 3,
    firstName: 'Petro',
    lastName: '',
    email: 'contact3@icloud.com',
    phoneNumber: '333',
    description: '',
    company: '',
    isBlocked: false,
  },
];
